### ISSUE TITLE
Diagnose cell matching failures

### ISSUE THREAD

**Issue by danielsf** [AllenInstitute/ophys_nway_matching#67]
**Tasks**
- [x] Reach out to Michael Buice for the code he used to generate the plots in the email linked to in Epic #66
- [x] Verify that we can recreate his figures
- [x] Assemble a list of containers, experiments, and ROIs/cells for which cell matching seems to have failed

For those who, like me, can never remember, "container" is our word for the set of imaging sessions acquired in the same plane, [see here](https://allensdk.readthedocs.io/en/latest/_static/visual_behavior_2p/data_structure.png).

**Comment by morriscb** [comment]
From Michael Buice: Here are a list of containers with experiments where he is noticing the issue.



MultiscopeSignalNoise container IDs:
1031935287, 1031935297, 1031935281, 1031935294, 1031935291,
1031935284, 1031935278, 1031935250, 1031935259, 1031935272,
1031935266, 1031935269, 1031935263, 1031935253, 1031935256,
1031935275, 1031935764, 1031935767, 1031935761, 1031935758,
1031935779, 1031935770, 1031935776, 1031935773, 1031935244,
1031935224, 1031935231, 1031935234, 1031935237, 1031935247,
1031935241, 1031935228, 1031935609, 1031935602, 1031935616,
1031935613, 1031935619, 1031935625, 1031935605, 1031935622,
1031935530, 1031935521, 1031935518, 1031935515, 1031935524,
1031935509, 1031935512, 1031935527

Scott submitted 1031935287 to the NWAY REMAP queue. I checked the results and they look reasonable in two ways. First, the output from the actual process produces matches that are within 10 pixels before applying the transforms to map the data on top of each other. I think this shows the code is producing reasonable results and the issue is not in the process itself. Second: I checked that this queue was loading the expected data in LIMS. I checked that the specimen ids, ROI ids, and experiment ids would be what I expect from the json file and confirmed for at least 5 specimens that this was the case.

The next step I think is tracing backward through Michael Buice's code and checking that the data being loaded and processed is correct. He sent me it.

To run his script from the email, you need his fork of [AlenSDK](https://github.com/mabuice/AllenSDK/tree/mesoscope-mabuice/allensdk/brain_observatory/behavior), his scripts are [here](https://github.com/AllenInstitute/bob_response_models/blob/trial_average/cell_matching_stats.py), and finally you need the data [here](https://github.com/alleninstitute/signalnoiseanalysis). I have started runs of this script and it seems to work though I ran out of memory on my Allen desktop and have switched to using Synapse. Will update this ticket when I know more after that job complets and I take a look at the data.

**Comment by morriscb** [comment]
Ended up finding that the majority of issues here had to do with running the data through the queue progressively, that is as experiments were added to the container. Because the default queue can't update already written cell_specimen_ids, the data ended up in a strange state that was a mixture of different matches. Below is the full email I sent to Michael Buice explaining the issue.

> > Hi Michael and Marina,
> 
> I think I have an understanding of what is happening with the MultiscopeSignalNoise dataset and potentially others. My quick ask to test my hypothesis is if it would be possible for me to run container 1031935764 (and eventually others) through the OPHYS_NWAY_CELL_MATCHING_REMAP_SPECIMENS_QUEUE to confirm what I think is happening.
> 
> The short of it is that it looks like the MultiscopeSignalNoise was run through the nway matching queue piecemeal as sessions were taken and experiments where added/made available in the container. Since the default OPHYS_NWAY_CELL_MATCHING_QUEUE can't make updates to the cell_specimen_ids for a given ROI once they are set, this left the data in a strange state in LIMS. This is due as the nway code potentially founding different and new matches when fed more data to register and associate ROIs over but being unable to change already created cell_specimen_ids. I think this explains the strange state of the cell_specimen_ids on LIMS and the fact that some matches could potentially break the distance limit set by the code. You can see this if you try to match up the matches that are in the json file output by the nway code to the matches that are stored in LIMS. I've written up a jupyter notebook (attached in html and ipynb) to illustrate what I mean. The good news is that it seems Scott's run of OPHYS_NWAY_CELL_MATCHING_REMAP_SPECIMENS_QUEUE on container 1031935287 was able to fix the cell_rois and associated cell_specimen_ids in LIMS. This is why I'd like to run 1031935764 through the code to confirm this to be the case. Michael, you did mention that it didn't look like 1031935287 improved, however, I can at least confirm, as is shown in the notebook, that the output of the container run by Scott is now what stored in LIMS. The opposite is true for 1031935764 as none of the json files stored for that container can be fully matched to what is in LIMS.
> 
> A secondary issue I discovered while looking into this (though likely related) is that the data quality of the average images that are being feed to the nway matcher for MultiscopeSignalNoise have an extremely low dynamic range of values. This is mostly likely true of other data run through the legacy segmentor/motion correction. If you look at the attached file avgInt_a1x.png produced by the legacy code, it doesn't look like much. This is due to the values in the png only spanning from integers of 0 to 30-ish rather than the full 256 values the 8-bit png allows. I'm going to assert that this doesn't help the image registration process within the matcher. I found that there were roughly 10% fewer ROIs that were unmatched when I re-ran one of the containers though nway matching outside of LIMS, using average images I created that spanned the full dynamic range. I also ran an experiment from one of the containers though the ophys_etl, suite2p motion correction wrapper and found that the png was much less washed out compared to even the ones I produced myself from the legacy motion stack. I think this has more to do with the legacy code potentially writing negative dummy values than the quality of the motion correction as the sharpness of the images doesn't look to be wildly different. I've attached a file comparison.pdf to show what I mean. The left image is the avgInt_a1x.png file produced by the legacy segmentor and used in by nway code, the middle image is my average image produced from the legacy motion corrected stack, and the right image is the output from ophys_etl/suite2p. All the images are plotted to the same stretch of 0 to 255. You can see that even my image produced form the legacy motion stack is still fairly washed out compared to the suite2/ophys_etl image. These are from experiment 1036533138 if you are curious but I have seen the same issue for other experiments across containers.
> 
> My hope is that by running the containers through the OPHYS_NWAY_CELL_MATCHING_REMAP_SPECIMENS_QUEUE, the MultiscopeSignalNoise can be fixed relative to their current state, though in the future we may want re-run these through the current version of the ophys_etl pipeline/queue.
> 
> Thanks for bearing with while I simultaneously attempted to learn how the LIMS queues/nway code worked and diagnose the issue. The good news is I feel like I learned something.
> 
> Thanks and enjoy your weekend!
> Chris

[Here is the link the notebook.](https://alleninstitute-my.sharepoint.com/:u:/g/personal/chris_morrison_alleninstitute_org/EedmYRZc1pNIqKPsJ88I1FEB8RZNss5tzZpsWuKugY3XUA?e=GtiaxD).
[Here's the link to the average image.](https://alleninstitute-my.sharepoint.com/:i:/g/personal/chris_morrison_alleninstitute_org/EW6KCTxpQ1hGgAcAB38EapIByJhhDLvHYVDTOAaqUkqXFw?e=W66v0d)
[And finally the link to the comparison.](https://alleninstitute-my.sharepoint.com/:b:/g/personal/chris_morrison_alleninstitute_org/Eb7hRvr1CkFBqkX7ympuHk8B-Cjs8_l-4EU0cbhWtP3UrA?e=xhLj5B)

Running 1031935764 through the REMAP queue indeed ended up fixing the issue. I've since submitted the remaining containers through the queue to similar success and consider the initial issue closed. Upon running the containers there were additional failures found, some related to the png issue innumerated in this ticket. I'll cronical these new failures in #68.
